version: "3.7"
services:
  flask_server:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    image: python:3.7-alpine
    links:
      - database:database
    restart: always
    ports:
      - 7777:7777
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: database

  database:
    container_name: db
    image: postgres:latest
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/dump.sql

